import { useMemo } from 'react';

const iconscategories = [
  {
    name: "Grocery",
    imgSrc: "/images/websiteicons/grocery.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Bakery",
    imgSrc: "/images/websiteicons/bakery.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Healthy",
    imgSrc: "/images/websiteicons/healthy-food.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Desserts",
    imgSrc: "/images/websiteicons/desserts.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Fruits & Vegetables",
    imgSrc: "/images/websiteicons/fruit-and-vegetables.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Dairy & Eggs",
    imgSrc: "/images/websiteicons/dairy-and-eggs.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Meat",
    imgSrc: "/images/websiteicons/meat.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Seafood",
    imgSrc: "/images/websiteicons/seafood.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Beverages",
    imgSrc: "/images/websiteicons/beverages.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Snacks & Sweets",
    imgSrc: "/images/websiteicons/snacks-and-sweets.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Household Essentials",
    imgSrc: "/images/websiteicons/household-essentials.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Pharmaceuticals",
    imgSrc: "/images/websiteicons/pharmaceuticals.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Baby",
    imgSrc: "/images/websiteicons/baby.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Pet Supplies",
    imgSrc: "/images/websiteicons/pet-food.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Frozen Foods",
    imgSrc: "/images/websiteicons/frozen-food.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Fast Food",
    imgSrc: "/images/websiteicons/fast-food.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Restaurant",
    imgSrc: "/images/websiteicons/restaurant.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "International Foods",
    imgSrc: "/images/websiteicons/international-food.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Alcohol",
    imgSrc: "/images/websiteicons/alcohol.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  // ... other categories
];

const categoriescards = [
  {
    name: "Grocery",
    imgSrc: "/images/cardcategories/cardgrocery.png",
    href: "/LP/Khomas/Towns/Stores",
  },
  {
    name: "Bakery",
    imgSrc: "/images/cardcategories/cardbakery.png",
    href: "/en/discovery/category/bakery",
  },
  {
    name: "Healthy",
    imgSrc: "/images/cardcategories/card-healthy-food.png",
    href: "/en/discovery/category/healthy",
  },
  {
    name: "Desserts",
    imgSrc: "/images/cardcategories/carddesserts.png",
    href: "/en/discovery/category/desserts",
  },
  {
    name: "Fruits & Vegetables",
    imgSrc: "/images/cardcategories/card-fruits-and-vegetables.png",
    href: "/en/discovery/category/fruits-vegetables",
  },
  {
    name: "Dairy & Eggs",
    imgSrc: "/images/cardcategories/card-dairy-and-eggs.png",
    href: "/en/discovery/category/dairy-eggs",
  },
  {
    name: "Meat",
    imgSrc: "/images/cardcategories/cardmeat.png",
    href: "/en/discovery/category/meat",
  },
  {
    name: "Seafood",
    imgSrc: "/images/cardcategories/cardseafood.png",
    href: "/en/discovery/category/seafood",
  },
  {
    name: "Beverages",
    imgSrc: "/images/cardcategories/cardbeverages.png",
    href: "/en/discovery/category/beverages",
  },
  {
    name: "Snacks & Sweets",
    imgSrc: "/images/cardcategories/card-snacks-and-sweets.png",
    href: "/en/discovery/category/snacks-sweets",
  },
  {
    name: "Household Essentials",
    imgSrc: "/images/cardcategories/card-household-essentials.png",
    href: "/en/discovery/category/household-essentials",
  },
  {
    name: "Pharmaceuticals",
    imgSrc: "/images/cardcategories/cardpharmaceuticals.png",
    href: "/en/discovery/category/household-essentials",
  },
  {
    name: "Baby",
    imgSrc: "/images/cardcategories/cardbaby.png",
    href: "/en/discovery/category/baby",
  },
  {
    name: "Pet Supplies",
    imgSrc: "/images/cardcategories/card-pet-food.png",
    href: "/en/discovery/category/pet-supplies",
  },
  {
    name: "Frozen Foods",
    imgSrc: "/images/cardcategories/card-frozen-food.png",
    href: "/en/discovery/category/frozen-foods",
  },
  {
    name: "Fast Food",
    imgSrc: "/images/cardcategories/card-fast-food.png",
    href: "/en/discovery/category/fast-food",
  },
  {
    name: "Restaurant",
    imgSrc: "/images/cardcategories/cardrestaurant.png",
    href: "/en/discovery/category/restaurant",
  },
  {
    name: "International Foods",
    imgSrc: "/images/cardcategories/card-international-food.png",
    href: "/en/discovery/category/international-foods",
  },
  {
    name: "Alcohol",
    imgSrc: "/images/cardcategories/cardalcohol.png",
    href: "/en/discovery/category/alcohol",
  },
  // ... other categories
];

const storescards1 = [
  {
    name: "Checkers",
    imgSrc: "/images/supermarkets/checkers.png",
    href: "/LP/Khomas/Towns/Store/Checkers",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "Shoprite",
    imgSrc: "/images/supermarkets/shoprite.png",
    href: "/en/discovery/category/shoprite",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "Pick n Pay",
    imgSrc: "/images/supermarkets/picknpay.png",
    href: "/en/discovery/category/picknpay",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "Spar",
    imgSrc: "/images/supermarkets/spar.png",
    href: "/en/discovery/category/spar",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "Woermann Brock",
    imgSrc: "/images/supermarkets/woermannbrock.png",
    href: "/en/discovery/category/woermannbrock",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "OK Foods",
    imgSrc: "/images/supermarkets/okfoods.png",
    href: "/en/discovery/category/okfoods",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "Choppies",
    imgSrc: "/images/supermarkets/choppies.png",
    href: "/en/discovery/category/choppies",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Food Lover's Market",
    imgSrc: "/images/supermarkets/foodlovers.png",
    href: "/en/discovery/category/foodloversmarket",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Metro",
    imgSrc: "/images/supermarkets/metro.png",
    href: "/en/discovery/category/metro",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Joe's Beerhouse",
    imgSrc: "/images/restaurants/joesbeerhouse.png",
    href: "/LP/Khomas/Towns/Restaurant/JoesBeerhouse",
    storetype: "Restaurant",
    isEtomartStore: true,
    priceRange: "N$$$",
    cuisine: "German",
    pickupTime: "20–40 min",
    deliveryTime: false,
  },
  {
    name: "The Stellenbosch Wine Bar",
    imgSrc: "/images/restaurants/stellenbosch.png",
    href: "/en/discovery/category/stellenbosch",
    storetype: "Restaurant",
    isEtomartStore: false,
    priceRange: "N$$$",
    cuisine: "International",
    pickupTime: "20–40 min",
    deliveryTime: false,
  },
  {
    name: "O Portuga",
    imgSrc: "/images/restaurants/oportuga.png",
    href: "/en/discovery/category/oportuga",
    storetype: "Restaurant",
    isEtomartStore: false,
    priceRange: "N$$$",
    cuisine: "Portuguese",
    pickupTime: "20–40 min",
    deliveryTime: false,
  },
  {
    name: "The Social",
    imgSrc: "/images/restaurants/thesocial.png",
    href: "/en/discovery/category/thesocial",
    storetype: "Restaurant",
    isEtomartStore: true,
    priceRange: "N$$$",
    cuisine: "Bar & Grill",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Sardinia Blue Olive",
    imgSrc: "/images/restaurants/sardiniablueolive.png",
    href: "/en/discovery/category/sardiniablueolive",
    storetype: "Restaurant",
    isEtomartStore: false,
    priceRange: "N$$$",
    cuisine: "Mediterranean",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Slowtown Coffee Roasters",
    imgSrc: "/images/restaurants/slowtown.png",
    href: "/en/discovery/category/slowtown",
    storetype: "Café",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Coffee",
    pickupTime: "10–20 min",
    deliveryTime: false,
  },
  {
    name: "Dis-Chem",
    imgSrc: "/images/pharmacies/dischem.png",
    href: "/en/discovery/category/dischem",
    storetype: "Pharmacy",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: false,
  },
  {
    name: "Clicks Pharmacy",
    imgSrc: "/images/pharmacies/clicks.png",
    href: "/LP/Khomas/Towns/Pharmacy/Clicks",
    storetype: "Pharmacy",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Nampharm Pharmacy",
    imgSrc: "/images/pharmacies/nampharm.png",
    href: "/en/discovery/category/nampharm",
    storetype: "Pharmacy",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Alpha Pharm",
    imgSrc: "/images/pharmacies/alphapharm.png",
    href: "/en/discovery/category/alphapharm",
    storetype: "Pharmacy",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Medicine World",
    imgSrc: "/images/pharmacies/medicineworld.png",
    href: "/en/discovery/category/medicineworld",
    storetype: "Pharmacy",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "City Pharmacy",
    imgSrc: "/images/pharmacies/citypharmacy.png",
    href: "/en/discovery/category/citypharmacy",
    storetype: "Pharmacy",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: false,
  },
  // ... other stores
];

const storescards2 = [
  {
    name: "Dis-Chem",
    imgSrc: "/images/pharmacies/dischem.png",
    href: "/en/discovery/category/dischem",
    storetype: "Pharmacy",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: false,
  },
  {
    name: "Clicks Pharmacy",
    imgSrc: "/images/pharmacies/clicks.png",
    href: "/LP/Khomas/Towns/Pharmacy/Clicks",
    storetype: "Pharmacy",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Nampharm Pharmacy",
    imgSrc: "/images/pharmacies/nampharm.png",
    href: "/en/discovery/category/nampharm",
    storetype: "Pharmacy",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Alpha Pharm",
    imgSrc: "/images/pharmacies/alphapharm.png",
    href: "/en/discovery/category/alphapharm",
    storetype: "Pharmacy",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Medicine World",
    imgSrc: "/images/pharmacies/medicineworld.png",
    href: "/en/discovery/category/medicineworld",
    storetype: "Pharmacy",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "City Pharmacy",
    imgSrc: "/images/pharmacies/citypharmacy.png",
    href: "/en/discovery/category/citypharmacy",
    storetype: "Pharmacy",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Joe's Beerhouse",
    imgSrc: "/images/restaurants/joesbeerhouse.png",
    href: "/LP/Khomas/Towns/Restaurant/JoesBeerhouse",
    storetype: "Restaurant",
    isEtomartStore: true,
    priceRange: "N$$$",
    cuisine: "German",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "The Stellenbosch Wine Bar",
    imgSrc: "/images/restaurants/stellenbosch.png",
    href: "/en/discovery/category/stellenbosch",
    storetype: "Restaurant",
    isEtomartStore: false,
    priceRange: "N$$$",
    cuisine: "International",
    pickupTime: "20–40 min",
    deliveryTime: false,
  },
  {
    name: "O Portuga",
    imgSrc: "/images/restaurants/oportuga.png",
    href: "/en/discovery/category/oportuga",
    storetype: "Restaurant",
    isEtomartStore: false,
    priceRange: "N$$$",
    cuisine: "Portuguese",
    pickupTime: "20–40 min",
    deliveryTime: false,
  },
  {
    name: "The Social",
    imgSrc: "/images/restaurants/thesocial.png",
    href: "/en/discovery/category/thesocial",
    storetype: "Restaurant",
    isEtomartStore: true,
    priceRange: "N$$$",
    cuisine: "Bar & Grill",
    pickupTime: "20–40 min",
    deliveryTime: false,
  },
  {
    name: "Sardinia Blue Olive",
    imgSrc: "/images/restaurants/sardiniablueolive.png",
    href: "/en/discovery/category/sardiniablueolive",
    storetype: "Restaurant",
    isEtomartStore: false,
    priceRange: "N$$$",
    cuisine: "Mediterranean",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Slowtown Coffee Roasters",
    imgSrc: "/images/restaurants/slowtown.png",
    href: "/en/discovery/category/slowtown",
    storetype: "Café",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Coffee",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Checkers",
    imgSrc: "/images/supermarkets/checkers.png",
    href: "/LP/Khomas/Towns/Store/Checkers",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "Shoprite",
    imgSrc: "/images/supermarkets/shoprite.png",
    href: "/en/discovery/category/shoprite",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "Pick n Pay",
    imgSrc: "/images/supermarkets/picknpay.png",
    href: "/en/discovery/category/picknpay",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Spar",
    imgSrc: "/images/supermarkets/spar.png",
    href: "/en/discovery/category/spar",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Woermann Brock",
    imgSrc: "/images/supermarkets/woermannbrock.png",
    href: "/en/discovery/category/woermannbrock",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "OK Foods",
    imgSrc: "/images/supermarkets/okfoods.png",
    href: "/en/discovery/category/okfoods",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "Choppies",
    imgSrc: "/images/supermarkets/choppies.png",
    href: "/en/discovery/category/choppies",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  {
    name: "Food Lover's Market",
    imgSrc: "/images/supermarkets/foodlovers.png",
    href: "/en/discovery/category/foodloversmarket",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Metro",
    imgSrc: "/images/supermarkets/metro.png",
    href: "/en/discovery/category/metro",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  // ... other stores
];

const supermarkets = [
  {
    name: "Checkers",
    imgSrc: "/images/supermarkets/checkers.png",
    href: "/LP/Khomas/Towns/Store/Checkers",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Shoprite",
    imgSrc: "/images/supermarkets/shoprite.png",
    href: "/en/discovery/category/shoprite",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Pick n Pay",
    imgSrc: "/images/supermarkets/picknpay.png",
    href: "/en/discovery/category/picknpay",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Spar",
    imgSrc: "/images/supermarkets/spar.png",
    href: "/en/discovery/category/spar",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Woermann Brock",
    imgSrc: "/images/supermarkets/woermannbrock.png",
    href: "/en/discovery/category/woermannbrock",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "OK Foods",
    imgSrc: "/images/supermarkets/okfoods.png",
    href: "/en/discovery/category/okfoods",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Choppies",
    imgSrc: "/images/supermarkets/choppies.png",
    href: "/en/discovery/category/choppies",
    storetype: "Supermarket",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Food Lover's Market",
    imgSrc: "/images/supermarkets/foodlovers.png",
    href: "/en/discovery/category/foodloversmarket",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: true,
  },
  {
    name: "Metro",
    imgSrc: "/images/supermarkets/metro.png",
    href: "/en/discovery/category/metro",
    storetype: "Supermarket",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Supermarket",
    pickupTime: "15–30 min",
    deliveryTime: false,
  },
  // ... other supermarkets
];

const restaurants = [
  {
    name: "The Stellenbosch Wine Bar",
    imgSrc: "/images/restaurants/stellenbosch.png",
    href: "/en/discovery/category/stellenbosch",
    storetype: "Restaurant",
    isEtomartStore: false,
    priceRange: "N$$$",
    cuisine: "International",
    pickupTime: "20–40 min",
    deliveryTime: false,
  },
  {
    name: "O Portuga",
    imgSrc: "/images/restaurants/oportuga.png",
    href: "/en/discovery/category/oportuga",
    storetype: "Restaurant",
    isEtomartStore: false,
    priceRange: "N$$$",
    cuisine: "Portuguese",
    pickupTime: "20–40 min",
    deliveryTime: false,
  },
  {
    name: "The Social",
    imgSrc: "/images/restaurants/thesocial.png",
    href: "/en/discovery/category/thesocial",
    storetype: "Restaurant",
    isEtomartStore: true,
    priceRange: "N$$$",
    cuisine: "Bar & Grill",
    pickupTime: "20–40 min",
    deliveryTime: false,
  },
  {
    name: "Joe's Beerhouse",
    imgSrc: "/images/restaurants/joesbeerhouse.png",
    href: "/LP/Khomas/Towns/Restaurant/JoesBeerhouse",
    storetype: "Restaurant",
    isEtomartStore: true,
    priceRange: "N$$$",
    cuisine: "German",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Sardinia Blue Olive",
    imgSrc: "/images/restaurants/sardiniablueolive.png",
    href: "/en/discovery/category/sardiniablueolive",
    storetype: "Restaurant",
    isEtomartStore: false,
    priceRange: "N$$$",
    cuisine: "Mediterranean",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Slowtown Coffee Roasters",
    imgSrc: "/images/restaurants/slowtown.png",
    href: "/en/discovery/category/slowtown",
    storetype: "Café",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Coffee",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  // ... other restaurants
];

const pharmacies = [
  {
    name: "Dis-Chem",
    imgSrc: "/images/pharmacies/dischem.png",
    href: "/en/discovery/category/dischem",
    storetype: "Pharmacy",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Clicks Pharmacy",
    imgSrc: "/images/pharmacies/clicks.png",
    href: "/LP/Khomas/Towns/Pharmacy/Clicks",
    storetype: "Pharmacy",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Nampharm Pharmacy",
    imgSrc: "/images/pharmacies/nampharm.png",
    href: "/en/discovery/category/nampharm",
    storetype: "Pharmacy",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "Alpha Pharm",
    imgSrc: "/images/pharmacies/alphapharm.png",
    href: "/en/discovery/category/alphapharm",
    storetype: "Pharmacy",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: false,
  },
  {
    name: "Medicine World",
    imgSrc: "/images/pharmacies/medicineworld.png",
    href: "/en/discovery/category/medicineworld",
    storetype: "Pharmacy",
    isEtomartStore: false,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  {
    name: "City Pharmacy",
    imgSrc: "/images/pharmacies/citypharmacy.png",
    href: "/en/discovery/category/citypharmacy",
    storetype: "Pharmacy",
    isEtomartStore: true,
    priceRange: "N$$",
    cuisine: "Health & Wellness",
    pickupTime: "10–20 min",
    deliveryTime: true,
  },
  // ... other pharmacies
];

const cards = [
  {
    title: "Fresh Produce",
    description:
      "Get farm-fresh fruits and vegetables delivered to your doorstep. Quality you can trust, convenience you will love.",
    image: "/images/1.webp",
  },
  {
    title: "Dairy Products",
    description:
      "Order fresh milk, cheese, yogurt, and more. Fast delivery and reliable service at your fingertips.",
    image: "/images/2.webp",
  },
  {
    title: "Bakery Goods",
    description:
      "Craving fresh bread and pastries? Get delicious bakery items delivered from local bakers. Quick and easy.",
    image: "/images/3.webp",
  },
  {
    title: "Pantry Staples",
    description:
      "Stock up on pantry essentials with our fast and convenient delivery service. Everything you need in one place.",
    image:
      "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80",
  },
  {
    title: "Beverages",
    description:
      "Shop a wide range of beverages, from juices to sodas. Refresh your day with our top selections.",
    image: "/images/4.webp",
  },
  // ... other cards
];

const aboutus = [
  {
    title: "Easy Ordering",
    description:
      "Our user-friendly platform makes it simple to order your favorite groceries with just a few clicks.",
    image: "/images/1EO1.png",
  },
  {
    title: "Fast Delivery",
    description:
      "Enjoy lightning-fast delivery times, ensuring your groceries arrive fresh and on time.",
    image: "/images/2FD2.png",
  },
  {
    title: "Customer Support",
    description:
      "Our dedicated support team is here to help you with any questions or issues, 24/7.",
    image: "/images/3CS3.png",
  },
  // ... other about us items
];

export function useIconsCategories() {
  return useMemo(() => iconscategories, []);
}

export function useCategoriesCards() {
  return useMemo(() => categoriescards, []);
}

export function useStoresCards1() {
  return useMemo(() => storescards1, []);
}

export function useStoresCards2() {
  return useMemo(() => storescards2, []);
}

export function useSupermarkets() {
  return useMemo(() => supermarkets, []);
}

export function useRestaurants() {
  return useMemo(() => restaurants, []);
}

export function usePharmacies() {
  return useMemo(() => pharmacies, []);
}

export function useCards() {
  return useMemo(() => cards, []);
}

export function useAboutUs() {
  return useMemo(() => aboutus, []);
}