import { useMemo } from 'react';

const navcategories = [
  {
    name: "Produce",
    imgSrc: "/images/1.webp",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "Dairy",
    imgSrc: "/images/2.webp",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
  {
    name: "Meat & Seafood",
    imgSrc: "/images/meat.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "Bakery",
    imgSrc: "/images/bread.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
  {
    name: "Frozen Foods",
    imgSrc: "/images/frozen.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "Snacks & Confectionery",
    imgSrc: "/images/sweets.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
  {
    name: "Beverages",
    imgSrc: "/images/beverages.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "Pantry Staples",
    imgSrc: "/images/pantry.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
  {
    name: "Household Essentials",
    imgSrc: "/images/hh.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "Personal Care",
    imgSrc: "/images/pc.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
  {
    name: "Health & Wellness",
    imgSrc: "/images/hw.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "Pet Care",
    imgSrc: "/images/ps.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
  {
    name: "Baby Care",
    imgSrc: "/images/bp.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "Cleaning Supplies",
    imgSrc: "/images/CS.PNG",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
  {
    name: "Paper Goods",
    imgSrc: "/images/pg.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "International Foods",
    imgSrc: "/images/if.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
  {
    name: "Organic & Natural",
    imgSrc: "/images/on.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "Alcohol & Wine",
    imgSrc: "/images/aw.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
  {
    name: "Baking Essentials",
    imgSrc: "/images/bs.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-0",
  },
  {
    name: "Canned & Preserved Foods",
    imgSrc: "/images/cjg.png",
    href: "/en/isr/eilat/venue/123-alcohol-wine-eilat/items/menucategory-1",
  },
];

const cards = [
  {
    title: "Fresh Produce",
    description:
      "Get farm-fresh fruits and vegetables delivered to your doorstep. Quality you can trust, convenience you will love.",
    image: "/images/1.webp",
  },
  {
    title: "Dairy Products",
    description:
      "Order fresh milk, cheese, yogurt, and more. Fast delivery and reliable service at your fingertips.",
    image: "/images/2.webp",
  },
  {
    title: "Bakery Goods",
    description:
      "Craving fresh bread and pastries? Get delicious bakery items delivered from local bakers. Quick and easy.",
    image: "/images/3.webp",
  },
  {
    title: "Pantry Staples",
    description:
      "Stock up on pantry essentials with our fast and convenient delivery service. Everything you need in one place.",
    image:
      "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80",
  },
  {
    title: "Beverages",
    description:
      "Shop a wide range of beverages, from juices to sodas. Refresh your day with our top selections.",
    image: "/images/4.webp",
  },
  // Add more cards as needed
];

export const storecards = [
  {
    name: "Bread",
    imgSrc: "/images/supermarkets/bread.png",
    href: "/en/stores/bread/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Bakery",
    description: "Freshly baked bread loaf",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Milk",
    imgSrc: "/images/supermarkets/milk.png",
    href: "/en/stores/milk/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Dairy",
    description: "1 liter of whole milk",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Eggs",
    imgSrc: "/images/supermarkets/eggs.png",
    href: "/en/stores/eggs/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Dairy",
    description: "A dozen large eggs",
    pickupTime: "15–35 min",
    deliveryTime: false,
  },
  {
    name: "Chicken Breast",
    imgSrc: "/images/supermarkets/chicken-breast.png",
    href: "/en/stores/chicken-breast/",
    discount: 20,
    isEtomartStore: false,
    priceRange: "€€",
    type: "Meat & Seafood",
    description: "1 kg of fresh chicken breast",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Apples",
    imgSrc: "/images/supermarkets/apples.png",
    href: "/en/stores/apples/",
    discount: 10,
    isEtomartStore: false,
    priceRange: "€",
    type: "Produce",
    description: "A bag of fresh apples",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Butter",
    imgSrc: "/images/supermarkets/butter.png",
    href: "/en/stores/butter/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Dairy",
    description: "250g of unsalted butter",
    pickupTime: "15–35 min",
    deliveryTime: true,
  },
  {
    name: "Orange Juice",
    imgSrc: "/images/supermarkets/orange-juice.png",
    href: "/en/stores/orange-juice/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Beverages",
    description: "1 liter of fresh orange juice",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Cereal",
    imgSrc: "/images/supermarkets/cereal.png",
    href: "/en/stores/cereal/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Pantry Staples",
    description: "500g box of breakfast cereal",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Rice",
    imgSrc: "/images/supermarkets/rice.png",
    href: "/en/stores/rice/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Pantry Staples",
    description: "1 kg of long grain rice",
    pickupTime: "15–35 min",
    deliveryTime: true,
  },
  {
    name: "Tomatoes",
    imgSrc: "/images/supermarkets/tomatoes.png",
    href: "/en/stores/tomatoes/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Produce",
    description: "A bag of fresh tomatoes",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Pasta",
    imgSrc: "/images/supermarkets/pasta.png",
    href: "/en/stores/pasta/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Pantry Staples",
    description: "500g pack of spaghetti",
    pickupTime: "15–35 min",
    deliveryTime: true,
  },
  {
    name: "Cheese",
    imgSrc: "/images/supermarkets/cheese.png",
    href: "/en/stores/cheese/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€€",
    type: "Dairy",
    description: "250g block of cheddar cheese",
    pickupTime: "15–35 min",
    deliveryTime: true,
  },
  {
    name: "Yogurt",
    imgSrc: "/images/supermarkets/yogurt.png",
    href: "/en/stores/yogurt/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Dairy",
    description: "500g tub of Greek yogurt",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Beef",
    imgSrc: "/images/supermarkets/beef.png",
    href: "/en/stores/beef/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€€€",
    type: "Meat & Seafood",
    description: "1 kg of ground beef",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Salmon",
    imgSrc: "/images/supermarkets/salmon.png",
    href: "/en/stores/salmon/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€€€",
    type: "Meat & Seafood",
    description: "500g of fresh salmon fillet",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Broccoli",
    imgSrc: "/images/supermarkets/broccoli.png",
    href: "/en/stores/broccoli/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Produce",
    description: "Fresh broccoli crown",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Chips",
    imgSrc: "/images/supermarkets/chips.png",
    href: "/en/stores/chips/",
    discount: 5,
    isEtomartStore: false,
    priceRange: "€",
    type: "Snacks & Confectionery",
    description: "Family-size bag of potato chips",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Ice Cream",
    imgSrc: "/images/supermarkets/ice-cream.png",
    href: "/en/stores/ice-cream/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Frozen Foods",
    description: "1 liter of vanilla ice cream",
    pickupTime: "15–35 min",
    deliveryTime: true,
  },
  {
    name: "Pasta Sauce",
    imgSrc: "/images/supermarkets/pasta-sauce.png",
    href: "/en/stores/pasta-sauce/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Pantry Staples",
    description: "Jar of marinara sauce",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Laundry Detergent",
    imgSrc: "/images/supermarkets/laundry-detergent.png",
    href: "/en/stores/laundry-detergent/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€€",
    type: "Household Essentials",
    description: "1.5-liter bottle of laundry detergent",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Toilet Paper",
    imgSrc: "/images/supermarkets/toilet-paper.png",
    href: "/en/stores/toilet-paper/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Paper Goods",
    description: "12-pack of toilet paper rolls",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Dish Soap",
    imgSrc: "/images/supermarkets/dish-soap.png",
    href: "/en/stores/dish-soap/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Cleaning Supplies",
    description: "500ml bottle of dishwashing liquid",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Pet Food",
    imgSrc: "/images/supermarkets/pet-food.png",
    href: "/en/stores/pet-food/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€€",
    type: "Pet Care",
    description: "3kg bag of dry dog food",
    pickupTime: "20–40 min",
    deliveryTime: true,
  },
  {
    name: "Baby Wipes",
    imgSrc: "/images/supermarkets/baby-wipes.png",
    href: "/en/stores/baby-wipes/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Baby Care",
    description: "Pack of 80 baby wipes",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Granola Bars",
    imgSrc: "/images/supermarkets/granola-bars.png",
    href: "/en/stores/granola-bars/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Snacks & Confectionery",
    description: "Box of 10 granola bars",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Olive Oil",
    imgSrc: "/images/supermarkets/olive-oil.png",
    href: "/en/stores/olive-oil/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€€",
    type: "Pantry Staples",
    description: "500ml bottle of extra virgin olive oil",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Chocolate",
    imgSrc: "/images/supermarkets/chocolate.png",
    href: "/en/stores/chocolate/",
    discount: 10,
    isEtomartStore: false,
    priceRange: "€",
    type: "Snacks & Confectionery",
    description: "100g bar of dark chocolate",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Tea",
    imgSrc: "/images/supermarkets/tea.png",
    href: "/en/stores/tea/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€",
    type: "Beverages",
    description: "Box of 20 tea bags",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
  {
    name: "Coffee",
    imgSrc: "/images/supermarkets/coffee.png",
    href: "/en/stores/coffee/",
    discount: null,
    isEtomartStore: false,
    priceRange: "€€",
    type: "Beverages",
    description: "250g pack of ground coffee",
    pickupTime: "10–30 min",
    deliveryTime: true,
  },
];


const supermarkets = [
  {
    name: "Checkers",
    imgSrc: "/images/supermarkets/checkers.png",
    href: "/en/discovery/category/checkers",
  },
  {
    name: "Shoprite",
    imgSrc: "/images/supermarkets/shoprite.png",
    href: "/en/discovery/category/shoprite",
  },
  {
    name: "Pick n Pay",
    imgSrc: "/images/supermarkets/picknpay.png",
    href: "/en/discovery/category/picknpay",
  },
  {
    name: "Spar",
    imgSrc: "/images/supermarkets/spar.png",
    href: "/en/discovery/category/spar",
  },
  {
    name: "Woermann Brock",
    imgSrc: "/images/supermarkets/woermannbrock.png",
    href: "/en/discovery/category/woermannbrock",
  },
  {
    name: "OK Foods",
    imgSrc: "/images/supermarkets/okfoods.png",
    href: "/en/discovery/category/okfoods",
  },
  {
    name: "Choppies",
    imgSrc: "/images/supermarkets/choppies.png",
    href: "/en/discovery/category/choppies",
  },
  {
    name: "Food Lover's Market",
    imgSrc: "/images/supermarkets/foodlovers.png",
    href: "/en/discovery/category/foodloversmarket",
  },
  {
    name: "Metro",
    imgSrc: "/images/supermarkets/metro.png",
    href: "/en/discovery/category/metro",
  },
];

export function useNavcategories() {
  return useMemo(() => navcategories, []);
}

export function useCards() {
  return useMemo(() => cards, []);
}
export function useStoresCards() {
  return useMemo(() => storecards, []);
}

export function useSupermarkets() {
  return useMemo(() => supermarkets, []);
}

